rancherProjectId: "fu"
rancherClusterId: "bar"
namespaces:
  test:
    labels:
      label1: value1
    annotations:
      anno1: value1
secrets:
  test:
    vaultPath: "test"
    labels:
      label1: value1
      lebel2: value2
    annotations:
      anno1: value1
    data:
      secret1: value1
  regcred:
    vaultPath: test
    type: kubernetes.io/dockerconfigjson
    data:
      registry: registry
      username: admin
      password: my-password
configMaps:
  test:
    labels:
      label1: value1
    annotations:
      anno1: value1
    data:
      config1: value1
services:
  test:
    labels:
      label1: value1
    annotations:
      anno1: value1
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app.kubernetes.io/component: test
        app.kubernetes.io/instance: test
      sessionAffinity: None
      type: ClusterIP
quota:
  cpu: 3
  memory: 10Gi
  storage: 50Gi
limitRange:
  defaultRequest:
    cpu: 100m
    memory: 128Mi
  defaultLimit:
    cpu: 500m
    memory: 512Mi
  min:
    cpu: 50m
    memory: 64Mi
  max:
    cpu: 4
    memory: 12Gi