{{- $rancherClusterId := .Values.rancherClusterId }}
{{- $rancherProjectId := .Values.rancherProjectId }}
{{- range $name, $config := .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    {{- if and $rancherProjectId $rancherClusterId }}
    field.cattle.io/projectId: {{ $rancherClusterId }}:{{ $rancherProjectId }}
    {{- end }}
    {{- if $config.annotations }}
{{ toYaml $config.annotations | indent 4 }}
    {{- end }}
  {{- if or $rancherProjectId $config.labels }}
  labels:
    {{- if $rancherProjectId }}
    field.cattle.io/projectId: {{ $rancherProjectId }}
    {{- end }}
    {{- if $config.labels }}
{{ toYaml $config.labels | indent 4 }}
    {{- end }}
  {{- end }}
  name: {{ $name }}
{{- end }}