{{- range $name, $config := .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  {{- if or ( and .Values.rancherProjectId .Values.rancherClusterId) $config.annotations }}
  annotations:
    {{- if and .Values.rancherProjectId .Values.rancherClusterId }}
    field.cattle.io/projectId: {{ .Values.rancherClusterId }}:{{ .Values.rancherProjectId }}
    {{- end }}
    {{- if $config.annotations }}
    {{ toYaml $config.annotations | indent 4 }}
    {{- end }}
  {{- end }}
  {{- if or .Values.rancherProjectId $config.labels }}
  labels:
    {{- if .Values.rancherProjectId }}
    field.cattle.io/projectId: {{ .Values.rancherProjectId }}
    {{- end }}
    {{- if $config.labels }}
    {{ toYaml $config.labels | indent 4 }}
    {{- end }}
  {{- end }}
  name: {{ $name }}
{{- end }}