{{- range $name, $config := .Values.pvcs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  {{- if $config.annotations }}
  annotations:
{{ toYaml $config.annotations | indent 4 }}
  {{- end }}
  {{- if $config.labels }}
  labels:
{{ toYaml $config.labels | indent 4 }}
  {{- end }}
spec:
{{ toYaml $config.spec | indent 2 }}
{{- end }}