{{ $values := .Values}}
{{- range $name, $config := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  {{- if or $config.annotations $config.vaultPath }}
  annotations:
    {{- if $config.vaultPath }}
    avp.kubernetes.io/path: {{ tpl $config.vaultPath $values }}
    {{- end }}
    {{- if $config.annotations }}
{{ toYaml $config.annotations | indent 4 }}
    {{- end }}
  {{- end }}
  {{- if $config.labels }}
  labels:
{{ toYaml $config.labels | indent 4 }}
  {{- end }}
type: {{ $config.type | default "Opaque" }}
{{- if eq (default "Opaque" $config.type ) "kubernetes.io/dockerconfigjson" }}
stringData: 
  .dockerconfigjson: '{"auths":{"{{ $config.data.registry}}":{"username":"{{ $config.data.username }}","password":"{{ $config.data.password }}", "auth": "{{ $config.data.auth }}"}}}'
{{- else }}
data:
  {{- range $key, $data := $config.data }}
  {{ $key }}: {{ $data | b64enc }}
  {{- end}}
{{- end }}
{{- end }}